SELECT DISTINCT Price FROM ITEM
WHERE Type = "K3";

SELECT DISTINCT Client FROM SALE
WHERE SDate >= 19980101;

SELECT DISTINCT Descrip FROM ITEM
WHERE Type = "K3";

SELECT DISTINCT Position FROM SALE INNER JOIN STAFF
ON SALE.Staff = STAFF.Name
WHERE Item = "K11";